#! /bin/sh

### BEGIN INIT INFO
# Provides:          gweb-sb
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start gweb-sb at boot time
# Description:       Controls the gweb-sb
### END INIT INFO

APP_HOME=/usr/local/etc/gweb-sb
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=gweb-sb
DESC="gweb-sb Starter" 
APP_USER=ubuntu
ARGS="/usr/local/bin/gweb_run.sh"

#test -e $APP_HOME/$NAME.jar || exit 0

set -e

. /lib/lsb/init-functions

case "$1" in
  start)
	echo -n "Starting $DESC: "
	start-stop-daemon --start --chuid "$APP_USER" --chdir "$APP_HOME" --pidfile /var/run/$NAME.pid \
		--background --make-pidfile --exec bash -- $ARGS || true
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon --stop --signal 2 --quiet --pidfile /var/run/$NAME.pid || true
	echo "$NAME."
        rm -f /var/run/$NAME.pid
	;;
  restart)
	echo -n "Restarting $DESC: "
	start-stop-daemon --stop --signal 2 --quiet --pidfile /var/run/$NAME.pid || true
        rm -f /var/run/$NAME.pid
	sleep 1
        start-stop-daemon --start --chuid "$APP_USER" --chdir "$APP_HOME" --pidfile /var/run/$NAME.pid \
                --background --make-pidfile --exec bash -- $ARGS || true
        echo "$NAME."
	;;
  status)
	status_of_proc -p /var/run/$NAME.pid "$DAEMON" $NAME && exit 0 || exit $?
	;;
  *)
	echo "Usage: $NAME {start|stop|restart|status}" >&2
	exit 1
	;;
esac

exit 0